dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# Install sub-module using public HTTPS not SSH 
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - pip install coveralls pycodestyle pep257
  - python setup.py install
script:
  - pycodestyle --ignore=E501,W503 ocfl/*.py tests/*.py *.py
  - pep257 ocfl/*.py tests/*.py *.py
  - python setup.py test
after_success:
  - python setup.py coverage
  - coveralls
